name: Build and Deploy React App v0.81

on:
  push:
    branches:
      - server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.15.0

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        env:
          CI: false
          REACT_APP_BASE_API_URL: ${{ vars.REACT_APP_BASE_API_URL }}
          REACT_APP_WEB_SOCKET_URL:  ${{ vars.REACT_APP_WEB_SOCKET_URL }}
        run: npm run build

      - name: Upload build files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: build/
          target: ${{ vars.UPLOAD_PATH }}
